
export const _enquiryList = [
    {
      enquiryNumber: 'RESM/25/003',
      dateOfEnquiry: 'February 19, 2025',
      name: 'Maya Patel',
      phone: '0994 5444492',
      enquiryType: 'Self Enquiry',
      enquirySource: 'Social Media',
      count: 1,
      assignedTo: '-',
      status: 'Open',
      createdAt: 'February 22, 2025 7:30 PM',
    },
    {
      enquiryNumber: 'RESM/25/002',
      dateOfEnquiry: 'February 14, 2025',
      name: 'Michael Brown',
      phone: '0994 5444492',
      enquiryType: 'Self Enquiry',
      enquirySource: 'Friends',
      count: 1,
      assignedTo: '-',
      status: 'Open',
      createdAt: 'February 22, 2025 7:30 PM',
    },
    {
      enquiryNumber: 'RESM/25/001',
      dateOfEnquiry: 'February 9, 2025',
      name: 'Sarah Smith',
      phone: '0994 5444492',
      enquiryType: 'Force Enquiry',
      enquirySource: 'News Paper',
      count: 2,
      assignedTo: '-',
      status: 'Open',
      createdAt: 'February 22, 2025 7:30 PM',
    },
  ];